// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Infrastructure.Configurations
{
    public partial class AuditConfiguration : IEntityTypeConfiguration<Audit>
    {
        public void Configure(EntityTypeBuilder<Audit> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Audit__3214EC070E721ED5");

            entity.ToTable("Audit");

            entity.HasIndex(e => e.Action, "IX_Audit_Action");

            entity.HasIndex(e => e.ChangedBy, "IX_Audit_ChangedBy");

            entity.HasIndex(e => e.EntityId, "IX_Audit_EntityId");

            entity.HasIndex(e => e.EntityType, "IX_Audit_EntityType");

            entity.HasIndex(e => e.Timestamp, "IX_Audit_Timestamp");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Action).HasMaxLength(50);
            entity.Property(e => e.AuditType).HasMaxLength(50);
            entity.Property(e => e.ChangedBy).HasMaxLength(200);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(200)
                .HasDefaultValue("System");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.DeletedBy).HasMaxLength(200);
            entity.Property(e => e.EntityId).HasMaxLength(50);
            entity.Property(e => e.EntityType).HasMaxLength(100);
            entity.Property(e => e.Values).HasMaxLength(4000);
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.Timestamp).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.UpdatedBy).HasMaxLength(200);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Audit> entity);
    }
}
