// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Domain.Common;
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public  class Audit : AuditableEntity
{

    public string EntityType { get; set; } = null!;

    public string EntityId { get; set; } = null!;

    public string Action { get; set; } = null!;

    public string? OldValues { get; set; }

    public string? NewValues { get; set; }

    public string? ChangedBy { get; set; }

    public string? TableName { get; set; }

    public string AuditType { get; set; } = null!;

    public DateTime Timestamp { get; set; }

}