// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Domain.Common;
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public  class Citizen : AuditableEntity
{

    public string IdCardNumber { get; set; } = null!;

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public DateTime BirthDate { get; set; }

    public string AddressLine1 { get; set; } = null!;

    public string SubDistrict { get; set; } = null!;

    public string District { get; set; } = null!;

    public string Province { get; set; } = null!;

    public string PostalCode { get; set; } = null!;

    public string? IdCardImage { get; set; }
}