// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable enable

namespace Infrastructure.contexts;

public partial class CustomerContext : DbContext
{
    public CustomerContext(DbContextOptions<CustomerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Audit> Audits { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Province> Provinces { get; set; }

    public virtual DbSet<District> Districts { get; set; }

    public virtual DbSet<SubDistrict> SubDistricts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Infrastructure.Configurations.AuditConfiguration());
        modelBuilder.ApplyConfiguration(new Infrastructure.Configurations.CustomerConfiguration());
        modelBuilder.ApplyConfiguration(new Infrastructure.Configurations.ProvinceConfiguration());
        modelBuilder.ApplyConfiguration(new Infrastructure.Configurations.DistrictConfiguration());
        modelBuilder.ApplyConfiguration(new Infrastructure.Configurations.SubDistrictConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
